// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV91mPzdnP0-bbON3orFYu8zuB0e7Ql50',
    appId: '1:819052726140:web:55a32b4e1a4dcb86b246f9',
    messagingSenderId: '819052726140',
    projectId: 'todo-app-15c79',
    authDomain: 'todo-app-15c79.firebaseapp.com',
    storageBucket: 'todo-app-15c79.appspot.com',
    measurementId: 'G-4N72F4GRVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ_MaZSDuOzCvy9eqepEfmK6ujmq6Dwsg',
    appId: '1:819052726140:android:ca61e264b753889bb246f9',
    messagingSenderId: '819052726140',
    projectId: 'todo-app-15c79',
    storageBucket: 'todo-app-15c79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNt9ljSkdMyoKl5MPOKSZPI4Hy-O255u0',
    appId: '1:819052726140:ios:33d8d4c98c04691bb246f9',
    messagingSenderId: '819052726140',
    projectId: 'todo-app-15c79',
    storageBucket: 'todo-app-15c79.appspot.com',
    iosBundleId: 'com.chandra.firebaseTodoApp',
  );
}
